FROM golang:1.21.5-alpine3.19 AS build

RUN go install github.com/codesenberg/bombardier@latest

RUN touch /infinity

RUN echo "bombardier -c 50 http://go-server-compare:8086/health" > /infinity

CMD ["tail","-f","/infinity"]